usuario_rol:
    resource: "@UsuarioBundle/Resources/config/routing/rol.yml"
    prefix:   /roles

usuario_accion:
    resource: "@UsuarioBundle/Resources/config/routing/accion.yml"
    prefix:   /accion

usuario_funcionalidad:
    resource: "@UsuarioBundle/Resources/config/routing/funcionalidad.yml"
    prefix:   /funcionalidad

usuario_seguridad:
    resource: "@UsuarioBundle/Resources/config/routing/seguridad.yml"
    prefix:   /seguridad

usuario_log:
    resource: "@UsuarioBundle/Resources/config/routing/log.yml"
    prefix:   /logs

#rutas directas
usuario_acceso_denegado:
    path: /usuario/acceso-denegado
    defaults: { _controller: UsuarioBundle:Default:accessDenied}

cambiar_password:
    path:     /usuarios/{id}/cambiar_password
    defaults: { _controller: UsuarioBundle:CambiarPassword:cambiarPassword }


cambiar_password_form:
    path:     /usuarios/cambiar_password_form
    defaults: { _controller: UsuarioBundle:CambiarPassword:cambiarPasswordForm }
