services:
  usuario.form.usuario:
      class: UsuarioBundle\Form\UsuarioType
      tags:
          - { name: form.type }
      autowire: true

  usuario.form.accion:
        class: UsuarioBundle\Form\AccionType
        tags:
            - { name: form.type }
        autowire: true

  listener.request:
      class: UsuarioBundle\EventListener\FirewallListener
      autowire: true
      tags:
          - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

  listener.login_success:
      class:  UsuarioBundle\EventListener\AuthenticationSuccessListener
      autowire: true
      tags:
          - { name: kernel.event_listener, event: security.interactive_login, method: onSecurityInteractiveLogin }

  listener.acceso_denegado:
        class: UsuarioBundle\EventListener\AccesoDenegadoListener
        arguments:
          - "@doctrine.orm.default_entity_manager"
          - "@security.token_storage"
        tags:
            - { name: kernel.event_listener, event: acceso.denegado}

  security.manager:
      class: UsuarioBundle\Services\SecurityManager
      autowire: true

  Symfony\Bundle\FrameworkBundle\Routing\Router:
      alias: router.default
