rol_index:
    path:     /
    defaults: { _controller: "UsuarioBundle:Rol:index" }
    methods:  GET

rol_show:
    path:     /{id}/show
    defaults: { _controller: "UsuarioBundle:Rol:show" }
    methods:  GET

rol_new:
    path:     /new
    defaults: { _controller: "UsuarioBundle:Rol:new" }
    methods:  [GET, POST]

rol_edit:
    path:     /{id}/edit
    defaults: { _controller: "UsuarioBundle:Rol:edit" }
    methods:  [GET, POST]

rol_delete:
    path:     /{id}/delete
    defaults: { _controller: "UsuarioBundle:Rol:delete" }
    methods:  DELETE
