app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:  /

usuario:
    resource: "@UsuarioBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
