instrumento_index:
    path:     /
    defaults: { _controller: "AppBundle:Instrumento:index" }
    methods:  GET

instrumento_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Instrumento:show" }
    methods:  GET

instrumento_new:
    path:     /new
    defaults: { _controller: "AppBundle:Instrumento:new" }
    methods:  [GET, POST]

instrumento_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Instrumento:edit" }
    methods:  [GET, POST]

instrumento_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Instrumento:delete" }
    methods:  DELETE
