intervencion_index:
    path:     /pozo/{id}/
    defaults: { _controller: "AppBundle:Intervencion:index" }
    methods:  [GET,POST]

intervencion_equipo_index:
    path: /equipo/{id}/
    defaults: { _controller: "AppBundle:Intervencion:intervencionesEquipo" }
    methods: [GET,POST]
