mapa_pozos_intervenidos_actualmente:
    path:     /pozos_intervenidos_actualmente
    defaults: { _controller: "AppBundle:Mapa:pozosIntervenidosActualmente" }
    methods:  GET

mapa_trazado_pozos:
    path:     /trazado_pozo/{id}
    defaults: { _controller: "AppBundle:Mapa:trazadoPozosPorEquipo" }
    methods:  GET