pozo_index:
    path:     /
    defaults: { _controller: "AppBundle:Pozo:index" }
    methods:  GET

pozo_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Pozo:show" }
    methods:  GET

pozo_new:
    path:     /new
    defaults: { _controller: "AppBundle:Pozo:new" }
    methods:  [GET, POST]

pozo_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Pozo:edit" }
    methods:  [GET, POST]

pozo_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Pozo:delete" }
    methods:  DELETE
