recurso_index:
    path:     /
    defaults: { _controller: "AppBundle:Recurso:index" }
    methods:  GET

recurso_ver_pdf:
    path:     /{id}/ver_pdf
    defaults: { _controller: "AppBundle:Recurso:verPdf" }
    methods:  GET
